version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/TodoApi"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/TodoApi.Test"
    schedule:
      interval: "daily"
